
vars:
    httpPort: 8000
    dbUrl: 'mongodb://root:root@ds115752.mlab.com:15752/ideascloud-test'
httpServers:
    -   name: 'server'
        ports:
            http: '$httpPort'
        routers:

            -   name: 'webapps'
                description: 'Webapps Router'
                path: '/'
                routes:

                    # Demo service
                    -   method: 'GET'
                        path: '/'
                        pipeline:
                            -   staticsPath: '$business-tracker'

            -   name: 'api'
                description: 'API Router'
                path: '/api'
                routes:

                    # Demo service
                    -   method: 'POST'
                        path: '/business'
                        pipeline:
                            -   handler: '$bodyParserHandler'
                            -   handler: '$modelMongoTransactionHandler'
                                params:
                                    db: '$mongoDb'
                                    model: '$models/Business'
                                    resolveRoute: true
                                    transaction: 'register'
                                    transactionParams:
                                        - '&body'